language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - CARGO_DIR=rust/native
  - CARGO_DIR=c/rust
  - CARGO_PROFILE=
  - CARGO_PROFILE=--release
install:
  - rustup component add rustfmt clippy
script:
  - cd $CARGO_DIR && cargo build $CARGO_PROFILE --all --locked
  - cd $CARGO_DIR && cargo test $CARGO_PROFILE --all --locked
  - cd $CARGO_DIR && cargo check $CARGO_PROFILE --all
  - cd $CARGO_DIR && cargo clippy $CARGO_PROFILE
  - cd $CARGO_DIR && cargo fmt --all -- --check
matrix:
  allow_failures:
    - rust: nightly
