language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - CARGO_DIR=rust/native CARGO_PROFILE=
  - CARGO_DIR=rust/native CARGO_PROFILE=--release
  - CARGO_DIR=c/rust CARGO_PROFILE=
  - CARGO_DIR=c/rust CARGO_PROFILE=--release
install:
  - rustup component add rustfmt clippy
before_script:
  - cd $CARGO_DIR
script:
  - cargo build $CARGO_PROFILE --all --locked
  - cargo test $CARGO_PROFILE --all --locked
  - cargo check $CARGO_PROFILE --all
  - cargo clippy $CARGO_PROFILE
  - cargo fmt --all -- --check
matrix:
  allow_failures:
    - rust: nightly
